### PR TITLE
Armor Piercing damage type and magic damage comments

### PR DESCRIPTION
**Pull request by Dweblenod**
Adds new damage source for use in armorBypassingDamageMod() OnHitEffect. Removes TODO comments regarding Minestuck magical attacks, but it can be discussed below

### CODE REVIEW

**Comment by Dweblenod** [comment]
Regarding the magic damage, I can see indirectMagic() as an alternative to magic(). Not sure how others feels about the distinction

**Comment by kirderf1** [comment]
Yeah, `indirectMagic()` seems like a good choice.

**Comment by Dweblenod** [comment]
> Yeah, `indirectMagic()` seems like a good choice.

Looking at it closer, indirectMagic() requires both a projectile entity and the projectile entities owner. The projectile entity cannot be null

**Comment by kirderf1** [comment]
You could use the same entity for both. From `Guardian.GuardianAttackGoal.tick()`:
```java
livingentity.hurt(this.guardian.damageSources().indirectMagic(this.guardian, this.guardian), f);
```

**Comment by Dweblenod** [comment]
It hath been done

**Comment by kirderf1** [comment]
Would it make sense to rework the armor pierce damage type to have an entity source?

**Comment by Dweblenod** [comment]
> Would it make sense to rework the armor pierce damage type to have an entity source?

I would be down, but am not currently sure how to!

**Comment by kirderf1** [comment]
Alright did it for you and switched it to use player damage death messages.

**Review by kirderf1 — APPROVED** [review]

**Pull request merged**
