### PR TITLE
Minor Terrain component generation tweaks

### PR DESCRIPTION
**Pull request by Dweblenod**
Replaces coarse dirt used in Flora land rough terrain with mud, reduced frequency of end grass/end stone surface disks in End lands, changing rabbit and frog generation frequency

### CODE REVIEW

**Comment by kirderf1** [comment]
There are merge conflicts to resolve for this one.

**Comment by kirderf1** [comment]
And with 1.18 already merged, perhaps rephrase PR to focus on what it adds that wasn't in 1.18.

**Comment by Dweblenod** [comment]
Reset and cherry-picked!

**Review by kirderf1 — APPROVED** [review]
Looks good to go! Do you want to write something in the changelog as well before I merge, or should I take care of it myself after merging?

**Pull request merged**
