### PR TITLE
Credits and license for music tracks

### PR DESCRIPTION
**Pull request by kirderf1**
This is a start to building up both a credits file and a license file, starting off with all music tracks in the mod at this time.

The tracks by Catboss have been kept under the same license as the albums that they're sourced from (that being the "Land of Fans and Music" albums).
For all other tracks (which have been composed specifically for Minestuck), I have asked for and gotten permission from their authors to license them under CC BY-NC-SA 4.0.

### CODE REVIEW

**Comment by kirderf1** [comment]
I've lately wanted to change my approach from building up the credits and license file in parallel to instead focus more on the credits file first.

**Comment by Dweblenod** [comment]
Is there anything with this PR that you would like my help with while it is still a draft?

**Comment by kirderf1** [comment]
Not a lot, I think.
I am trying to decide if I'm gonna work more on the credits file in this PR, or if I instead should get this merged, and work on the credits file in a new PR. If you have any opinions on it, that would be nice.
Otherwise, the only thing would be to give an opinion on the format I've used so far.

**Comment by kirderf1** [comment]
Okay, I've decided to continue with the credits file on a new PR, which means that this should be ready to be reviewed and merged.

**Pull request merged**
