### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by amiwyn**

### CODE REVIEW

**Comment by amiwyn** [comment]
maybe one or two more fixes

**Comment by amiwyn** [comment]
you can merge the pr ill just reuse the same branch

**Comment by amiwyn** [comment]
- CANNOT HIT PARTS OF THE BASILISK NOT IN THE MAIN HITBOX
- THIS WAS ALREADY AN ISSUE BUT THE MACHINES ANIMATIONS PLAY UPON RELOADING WORLD

**Review by Dweblenod — APPROVED** [review]
Changes look good!

**Pull request merged**
